### ISSUE TITLE
Error when no payoutAddress is configured

### ISSUE THREAD

**Issue by Leonardiae** [VeriBlock/vbk-ri-btc#242]
When not payoutAddress is configured in application.config
`    payoutAddress: `
the APM throws an error when it's started: 
```
Copyright 2017-2020 Xenios SEZC
All rights reserved.
Distributed under the MIT software license, see the accompanying
file LICENSE or http://www.opensource.org/licenses/mit-license.php.

===[ VeriBlock Altchain Proof-of-Proof (PoP) Miner v0.4.10-dev.55 ]===
                https://www.veriblock.org/
                VeriBlock Explorer: https://explore.veriblock.org

See https://wiki.veriblock.org/index.php/Altchain_PoP_Miner for more details.

Type "help" to display a list of available commands

Exception in thread "main" java.lang.ExceptionInInitializerError
        at org.veriblock.miners.pop.AltchainPoPMiner$run$koin$1.invoke(AltchainPoPMiner.kt:50)
        at org.veriblock.miners.pop.AltchainPoPMiner$run$koin$1.invoke(AltchainPoPMiner.kt)
        at org.koin.core.context.GlobalContextKt.startKoin(GlobalContext.kt:72)
        at org.veriblock.miners.pop.AltchainPoPMiner.run(AltchainPoPMiner.kt:49)
        at org.veriblock.miners.pop.AltchainPoPMiner.main(AltchainPoPMiner.kt:115)
        at org.veriblock.miners.pop.AltchainPoPMiner.main(AltchainPoPMiner.kt)
Caused by: com.typesafe.config.ConfigException$Parse: .\application.conf: 18: Expecting close brace } or a comma, got ':' (if you intended ':' to be part of a key or string value, try enclosing the key or value in double quotes)
        at com.typesafe.config.impl.ConfigDocumentParser$ParseContext.parseError(ConfigDocumentParser.java:201)
        at com.typesafe.config.impl.ConfigDocumentParser$ParseContext.parseError(ConfigDocumentParser.java:197)
        at com.typesafe.config.impl.ConfigDocumentParser$ParseContext.parseObject(ConfigDocumentParser.java:528)
        at com.typesafe.config.impl.ConfigDocumentParser$ParseContext.parseValue(ConfigDocumentParser.java:247)
        at com.typesafe.config.impl.ConfigDocumentParser$ParseContext.consolidateValues(ConfigDocumentParser.java:152)
        at com.typesafe.config.impl.ConfigDocumentParser$ParseContext.parseObject(ConfigDocumentParser.java:473)
        at com.typesafe.config.impl.ConfigDocumentParser$ParseContext.parseValue(ConfigDocumentParser.java:247)
        at com.typesafe.config.impl.ConfigDocumentParser$ParseContext.parseObject(ConfigDocumentParser.java:458)
        at com.typesafe.config.impl.ConfigDocumentParser$ParseContext.parse(ConfigDocumentParser.java:648)
        at com.typesafe.config.impl.ConfigDocumentParser.parse(ConfigDocumentParser.java:14)
        at com.typesafe.config.impl.Parseable.rawParseValue(Parseable.java:260)
        at com.typesafe.config.impl.Parseable.rawParseValue(Parseable.java:248)
        at com.typesafe.config.impl.Parseable.parseValue(Parseable.java:180)
        at com.typesafe.config.impl.Parseable.parseValue(Parseable.java:174)
        at com.typesafe.config.impl.Parseable.parse(Parseable.java:299)
        at com.typesafe.config.ConfigFactory.parseFile(ConfigFactory.java:689)
        at com.typesafe.config.ConfigFactory.parseFile(ConfigFactory.java:703)
        at org.veriblock.core.utilities.ConfigurationKt.loadConfig(Configuration.kt:126)
        at org.veriblock.core.utilities.ConfigurationKt.access$loadConfig(Configuration.kt:1)
        at org.veriblock.core.utilities.Configuration.<init>(Configuration.kt:28)
        at org.veriblock.core.utilities.Configuration.<init>(Configuration.kt:24)
        at org.veriblock.miners.pop.MinerModuleKt$minerModule$1.invoke(MinerModule.kt:46)
        at org.veriblock.miners.pop.MinerModuleKt$minerModule$1.invoke(MinerModule.kt)
        at org.koin.dsl.ModuleKt.module(Module.kt:31)
        at org.koin.dsl.ModuleKt.module$default(Module.kt:29)
        at org.veriblock.miners.pop.MinerModuleKt.<clinit>(MinerModule.kt:44)
        ... 6 more
Application terminated unexpectedly, press any key to exit
```

**Comment by BernatCarbo** [comment]
This actually happens with all the configuration values, we will take a look!

**Comment by BernatCarbo** [comment]
There is not much to do about this, we will display the same message (not the whole stack) which directly shows that something is wrong with the configuration, and in such case, the default configuration will be auto-loaded.

https://github.com/VeriBlock/nodecore/pull/167

**Comment by Leonardiae** [comment]
Sounds good to me. Thanks.
